# ---
# - name: Install Jenkins
#   hosts: jenkins_nodes
#   become: true
#   tasks:
#     - name: Update apt packages
#       apt:
#         update_cache: yes
#         cache_valid_time: 3600

#     - name: Install Java (required for Jenkins)
#       apt:
#         name: openjdk-11-jre
#         state: present

#     - name: Add Jenkins repository
#       apt_repository:
#         repo: "deb http://pkg.jenkins.io/debian/ stable main"
#         state: present

#     - name: Install Jenkins
#       apt:
#         name: jenkins
#         state: present

#     - name: Start Jenkins service
#       service:
#         name: jenkins
#         state: started
#         enabled: yes

